// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("DiaryEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaryEntryId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiaryEntryId");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            DiaryEntryId = 1,
                            Content = "Went hiking with Miro!",
                            Created = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Went Hiking"
                        },
                        new
                        {
                            DiaryEntryId = 2,
                            Content = "Went biking with Miro!",
                            Created = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Went Biking"
                        },
                        new
                        {
                            DiaryEntryId = 3,
                            Content = "Went Shoping with Miro!",
                            Created = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Went Shoping"
                        },
                        new
                        {
                            DiaryEntryId = 4,
                            Content = "Went Diving with Miro!",
                            Created = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Went Diving"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
